[[constraint]]
  source = "https://github.com/gaocegege/k8s.git"
  name = "github.com/kubeflow/tf-operator"
  revision = "bf6199c51cc9b47f8a726947b5fac82432fcde83"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/kube-openapi"
